# Generated by Django 6.0.3 on 2026-04-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=10, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_clients', models.PositiveIntegerField(default=10, help_text='Máximo de clientes activos permitidos.')),
                ('has_ai', models.BooleanField(default=True)),
                ('has_human_coach', models.BooleanField(default=False)),
                ('has_video_call', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'billing_plan',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('past_due', 'Pago vencido'), ('canceled', 'Cancelada'), ('trialing', 'En prueba')], db_index=True, default='trialing', max_length=20)),
                ('stripe_sub_id', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('active_clients', models.PositiveIntegerField(default=0)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Exitoso'), ('pending', 'Pendiente'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'billing_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
