# Generated by Django 6.0.3 on 2026-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Almacenada en S3 en producción.', upload_to='progress_photos/%Y/%m/')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL pública de S3 (se rellena automáticamente).')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('angle', models.CharField(choices=[('front', 'Frente'), ('back', 'Espalda'), ('side_l', 'Perfil izquierdo'), ('side_r', 'Perfil derecho'), ('other', 'Otro')], default='front', max_length=8)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('visible_to_coach', models.BooleanField(default=True)),
                ('is_comparison', models.BooleanField(default=False, help_text='True si el coach la marcó como foto de comparación.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Progreso',
                'verbose_name_plural': 'Fotos de Progreso',
                'db_table': 'fitness_progressphoto',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
