# Generated by Django 6.0.3 on 2026-04-24 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressphoto',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='progress_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='progress.progresslog'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['client', 'week_number'], name='fitness_pro_client__32059b_idx'),
        ),
    ]
