# Generated by Django 6.0.3 on 2026-04-24 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('training_compliance', models.PositiveSmallIntegerField(default=0, help_text='% de sesiones de entrenamiento completadas', validators=[django.core.validators.MaxValueValidator(100)])),
                ('nutrition_compliance', models.PositiveSmallIntegerField(default=0, help_text='% de comidas del plan seguidas', validators=[django.core.validators.MaxValueValidator(100)])),
                ('hydration_compliance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('is_stagnant', models.BooleanField(db_index=True, default=False)),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('ai_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Progreso',
                'verbose_name_plural': 'Registros de Progreso',
                'db_table': 'fitness_progresslog',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('partial', 'Parcial'), ('skipped', 'Saltado')], default='completed', max_length=12)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rpe_avg', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'db_table': 'fitness_workoutsession',
                'ordering': ['-date'],
            },
        ),
    ]
