# Generated by Django 6.0.3 on 2026-04-24 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='training_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='plans.trainingday'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['client', 'date'], name='fitness_pro_client__67962d_idx'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['is_stagnant'], name='fitness_pro_is_stag_e76ea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progresslog',
            unique_together={('client', 'date')},
        ),
    ]
