# Generated by Django 6.0.3 on 2026-04-24 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(default='10', help_text="Ej: '8-12' o '15'", max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Rating of Perceived Exertion (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'fitness_exercise',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('mid_morning', 'Media Mañana'), ('lunch', 'Almuerzo'), ('pre_workout', 'Pre-entreno'), ('post_workout', 'Post-entreno'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carbs_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fat_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
                'db_table': 'fitness_meal',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('plan_type', models.CharField(choices=[('training', 'Entrenamiento'), ('nutrition', 'Nutrición'), ('combined', 'Combinado')], default='combined', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('paused', 'Pausado'), ('done', 'Completado')], db_index=True, default='draft', max_length=10)),
                ('created_by', models.CharField(choices=[('coach', 'Coach'), ('ai', 'IA'), ('both', 'IA + Coach')], default='ai', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('goals_notes', models.TextField(blank=True, default='')),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('total_weeks', models.PositiveSmallIntegerField(default=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carbs_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fat_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water_liters', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'fitness_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=12)),
                ('focus', models.CharField(blank=True, default='', help_text='Ej: Pecho + Tríceps', max_length=120)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Día de Entrenamiento',
                'verbose_name_plural': 'Días de Entrenamiento',
                'db_table': 'fitness_trainingday',
                'ordering': ['order'],
            },
        ),
    ]
