# Generated by Django 6.0.3 on 2026-05-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('video_call', 'Videollamada'), ('presential', 'Presencial'), ('monthly_check', 'Chequeo mensual'), ('initial', 'Evaluación inicial')], default='monthly_check', help_text='Tipo de sesión de coaching', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], db_index=True, default='scheduled', help_text='Estado actual de la sesión', max_length=12)),
                ('scheduled_at', models.DateTimeField(help_text='Fecha y hora de la sesión')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, help_text='Duración en minutos')),
                ('meeting_url', models.URLField(blank=True, default='', help_text='Link de Zoom/Meet para videollamadas')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Precio de la sesión', max_digits=8)),
                ('notes_coach', models.TextField(blank=True, default='', help_text='Notas internas del coach')),
                ('notes_client', models.TextField(blank=True, default='', help_text='Notas del cliente')),
                ('recording_url', models.URLField(blank=True, default='', help_text='Link a la grabación de la sesión')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Coaching',
                'verbose_name_plural': 'Sesiones de Coaching',
                'db_table': 'coaching_coachsession',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['coach', 'scheduled_at'], name='coaching_co_coach_i_e3a5d6_idx'), models.Index(fields=['client', 'scheduled_at'], name='coaching_co_client__6cc9cd_idx'), models.Index(fields=['status'], name='coaching_co_status_be4216_idx')],
            },
        ),
    ]
