# Generated by Django 6.0.3 on 2026-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Ganar músculo'), ('fat_loss', 'Perder grasa'), ('recomposition', 'Recomposición'), ('performance', 'Rendimiento'), ('maintenance', 'Mantenimiento')], default='muscle_gain', max_length=20)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=15)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentario'), ('light', 'Ligero (1-2 días/sem)'), ('moderate', 'Moderado (3-4 días/sem)'), ('active', 'Activo (5-6 días/sem)'), ('very_active', 'Muy activo (7 días/sem)')], default='moderate', max_length=15)),
                ('injuries', models.TextField(blank=True, default='', help_text='Lesiones o limitaciones físicas.')),
                ('medications', models.TextField(blank=True, default='')),
                ('equipment', models.TextField(blank=True, default='', help_text='Equipamiento disponible.')),
                ('notes', models.TextField(blank=True, default='')),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bmr_kcal', models.PositiveIntegerField(blank=True, help_text='Tasa metabólica basal.', null=True)),
                ('tdee_kcal', models.PositiveIntegerField(blank=True, help_text='Gasto calórico total diario.', null=True)),
                ('subscription_plan', models.CharField(blank=True, default='basic', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil del Atleta',
                'verbose_name_plural': 'Perfiles de Atletas',
                'db_table': 'fitness_clientprofile',
                'ordering': ['-joined_at'],
            },
        ),
    ]
