# Generated by Django 6.0.3 on 2026-04-24 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('specialty', models.CharField(choices=[('strength', 'Fuerza'), ('hypertrophy', 'Hipertrofia'), ('fat_loss', 'Pérdida de grasa'), ('powerlifting', 'Powerlifting'), ('crossfit', 'CrossFit'), ('nutrition', 'Nutrición deportiva'), ('general', 'Fitness general')], default='general', max_length=15)),
                ('certifications', models.TextField(blank=True, default='')),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('session_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('session_duration', models.PositiveSmallIntegerField(default=60, help_text='Duración en minutos')),
                ('max_clients', models.PositiveSmallIntegerField(default=20)),
                ('timezone', models.CharField(default='America/Bogota', max_length=50)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('avg_compliance', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del Coach',
                'verbose_name_plural': 'Perfiles de Coaches',
                'db_table': 'coaching_coachprofile',
            },
        ),
        migrations.CreateModel(
            name='CoachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('video_call', 'Videollamada'), ('presential', 'Presencial'), ('monthly_check', 'Chequeo mensual'), ('initial', 'Evaluación inicial')], default='monthly_check', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], db_index=True, default='scheduled', max_length=12)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_min', models.PositiveSmallIntegerField(default=60)),
                ('meeting_url', models.URLField(blank=True, default='', help_text='Link de Zoom/Meet.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes_coach', models.TextField(blank=True, default='')),
                ('notes_client', models.TextField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Coaching',
                'verbose_name_plural': 'Sesiones de Coaching',
                'db_table': 'coaching_coachsession',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Identificador único de la organización.', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'coaching_organization',
            },
        ),
    ]
