# Generated by Django 6.0.3 on 2026-05-01 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachsession',
            name='client',
        ),
        migrations.RemoveField(
            model_name='coachsession',
            name='coach',
        ),
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil del Coach', 'verbose_name_plural': 'Perfiles de Coaches'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='avg_compliance',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Cumplimiento promedio de sus clientes (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Biografía del coach'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='Certificaciones y credenciales (separadas por comas)'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='¿Está disponible para nuevos clientes?'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='¿Ha sido verificado por administración?'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='max_clients',
            field=models.PositiveSmallIntegerField(default=20, help_text='Máximo de clientes simultáneos'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Rating de 0 a 5', max_digits=3),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='session_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Duración estándar de sesión en minutos'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por sesión de coaching', max_digits=8),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='specialty',
            field=models.CharField(choices=[('strength', 'Fuerza'), ('hypertrophy', 'Hipertrofia'), ('fat_loss', 'Pérdida de grasa'), ('powerlifting', 'Powerlifting'), ('crossfit', 'CrossFit'), ('nutrition', 'Nutrición deportiva'), ('general', 'Fitness general')], default='general', help_text='Especialidad principal', max_length=15),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='timezone',
            field=models.CharField(default='America/Bogota', help_text='Zona horaria del coach', max_length=50),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='total_clients',
            field=models.PositiveIntegerField(default=0, help_text='Total de clientes que ha tenido'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='URL de sitio web personal'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Años de experiencia'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción de la organización'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la organización', null=True, upload_to='org_logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Nombre de la organización', max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Identificador único de la organización (URL-friendly)', unique=True),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['user'], name='coaching_co_user_id_0d68c4_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['specialty'], name='coaching_co_special_38c155_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['is_available'], name='coaching_co_is_avai_d265a4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='coaching_or_slug_cb4795_idx'),
        ),
        migrations.DeleteModel(
            name='CoachSession',
        ),
    ]
